version: '3'
services:
  app:
    restart: always
    container_name: yad_app
    build: .
    depends_on:
      - mongodb
  mongodb:
    restart: always
    image: "mongo:latest"
    environment:
      - AUTH=no
    container_name: yad_mongo
  router:
    restart: always
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
    container_name: yad_nginx