version: '3'
services:
  app:
    restart: always
    container_name: yad_app
    build: .
    ports:
      - "8080:8080"
  mongodb:
    restart: always
    image: "mongo:latest"
    environment:
      - AUTH=no
    container_name: yad_mongo