version: '3'
services:
  app:
    restart: unless-stopped
    container_name: yad_app
    build: .
    ports:
      - "5000:5000"
  mongodb:
    restart: unless-stopped
    image: "mongo:latest"
    environment:
      - AUTH=no
    container_name: yad_mongo